# Generated by Django 3.1.1 on 2020-10-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto',
            field=models.ImageField(blank=True, upload_to='', verbose_name='fotos/%d/%m/%Y/'),
        ),
    ]
